import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/component/Layout";
import Navbar from "@/component/Navbar";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId={process.env.GOOGLE_OAUTH_CLIENT_ID ?? ""}>
      <html lang="en">
        <body className={inter.className + `w-screen dark:bg-dark-background `}>
          {/* <Navbar /> */}
          <Layout>{children}</Layout>
        </body>
      </html>
    </GoogleOAuthProvider>
  );
}
